server.port: 8000

app:
  developer-service:
    host: localhost
    port: 8001
  recruiter-service:
    host: localhost
    port: 8002
  contact-service:
    host: localhost
    port: 8003

logging:
  level:
    root: INFO
    info.devlink: DEBUG

---
spring.profiles: docker

server.port: 8080

app:
  developer-service:
    host: developer
    port: 8080
  recruiter-service:
    host: recruiter
    port: 8080
  contact-service:
    host: contact
    port: 8080
