server.port: 8002

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recruiter-db

logging:
  level:
    root: INFO
    info.devlink: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
